### ISSUE TITLE
Ubuntu 中正文页眉不显示

### ISSUE THREAD

**Issue by delick** [silverriver/tex4cugb#1]
如图，正文章节中的页眉并没有显示出来。

![2019-05-31 17-21-55 的屏幕截图](https://i.loli.net/2019/05/31/5cf0f35af027a79433.png)

环境： Ubuntu 18.04 LTS, TeX 3.14159265 (TeX Live 2017/Debian)

**Comment by silverriver** [comment]
请问在编译过程中是否有warning或者错误，或者有没有log，目前很难看出来是哪里出的错

**Comment by delick** [comment]
[ms.log](https://github.com/silverriver/CUGBthesis/files/3243743/ms.log)
这是 Ubuntu 上的 log 文件。后来我尝试在 Windows 上测试，也是找不到页眉。

**Comment by silverriver** [comment]
哦，我想起来了，章节标题页没有页眉，后面几页就有了。
我记得这是fancyhdr这个包的默认行为，这样更加美观一些，章节标题页有页眉显得很丑。
当然，如果你非得想要章节标题页有页眉的话可以参考这个问题里面的方法：
https://tex.stackexchange.com/questions/117328/fancyhdr-does-not-apply-same-header-footer-on-chapter-and-non-chapter-pages
